#!/bin/bash

#check if salt-master is running

if [[ $(pgrep salt-master | wc -l) < 1 ]]; then
	salt-master -d
	curl -sS https://raw.githubusercontent.com/akalaj/saltstack/master/msm/hosts | cat >> /etc/hosts
else
	curl -sS https://raw.githubusercontent.com/akalaj/saltstack/master/msm/hosts | cat >> /etc/hosts
fi
